-- Creación de tablas --

CREATE TABLE ROL(
    ID_ROL INT PRIMARY KEY NOT NULL,
    NOMBRE_ROL VARCHAR2(100) NOT NULL,
    DESCRIPCION_ROL VARCHAR2(255)
);

CREATE TABLE UNIDAD_INTERNA(
    ID_UNIDAD_INTERNA INT PRIMARY KEY NOT NULL,
    NOMBRE_UNIDAD VARCHAR2(200) NOT NULL,
    DESCRIPCION_UNIDAD VARCHAR2(255)
);

CREATE TABLE USUARIO (
    RUT_USUARIO VARCHAR2(12) PRIMARY KEY NOT NULL,
    NOMBRE_USUARIO VARCHAR2(100) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO_USUARIO VARCHAR2(100) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(100) NOT NULL,
    NUM_TELEFONO INT NOT NULL,
    CORREO_ELECTRONICO VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ID_ROL_USUARIO INT NOT NULL,
    ID_UNIDAD_INTERNA_USUARIO INT NOT NULL,
    
    -- Foreign Key --
    CONSTRAINT FK_ROL_USUARIO 
        FOREIGN KEY (ID_ROL_USUARIO)
        REFERENCES ROL(ID_ROL),
        
    CONSTRAINT FK_ID_UNIDAD_INTERNA
        FOREIGN KEY (ID_UNIDAD_INTERNA_USUARIO)
        REFERENCES UNIDAD_INTERNA(ID_UNIDAD_INTERNA)
);


-- DESPUES DE CREAR LAS TABLAS DIRIGIRSE A BASE DE DATOS --- TABLAS -- SELECCIONAR TABLA -- SEGUNDO CLICK -- SELECCIONAR COLUMNA DE IDENTIDAD -- TIPO SECUENCIA DE COLUMNAS -- ACEPTAR 
-- UNA VEZ HECHO ESTE PROCESO, SE PROCEDE A HACER UN INSERT CON LA SIGUIENTE SINTAXIS INSERT INTO ROL (ATRIBUTO) INTO ('VALOR DE ATRIBUTO');
